### PR TITLE
Inline blocks child props

### PR DESCRIPTION
**Pull request by ncphillips**
[_Original PR by @sakulstra PR_](https://github.com/tinacms/tinacms/pull/1274)

this allows passing trough dynamic props

---

I've just gave tina-cms a spin after reading the next.js blogpost about it.
When experimenting a bit with the incredible cool inline features I faced some problems.

I wanted to make a collapsible list which roughly works like that:
```js
function InteractiveBlocks() {
  // ensure a single collapsible is open at a time
  const [expanded, setExpanded] = React.useState<number | false>(false);

  const handleChange = (panel: number) => (
    event: React.ChangeEvent<{}>,
    newExpanded: boolean
  ) => {
    setExpanded(newExpanded ? panel : false);
  };
  return (
   <InlineBlocks name="faqs" blocks={FAQ_BLOCKS} blockProps={{onChange: handleChange, expanded}} />
  )
}

const faq_item_template = {
  type: "faq_item",
  label: "Selling Point",
  defaultItem: {
    title: "How much is the fish",
    body: "8000 mark",
  },
};

const FAQ_BLOCKS = {
  faq_item: {
    Component: FaqItem,
    template: faq_item_template,
  },
};
```

---
## Todo: 

- [x] Updated docs PR approved

### CODE REVIEW

**Comment by sakulstra** [comment]
what happened here :D where did your comment go @ncphillips? Just wanted to read again what you suggested :sweat_smile:

**Comment by ncphillips** [comment]
Haha hey @sakulstra since the CI doesn't run on forks we merge PRs from forks into a new branch before merging into master. 

I should have linked to [the original PR](https://github.com/tinacms/tinacms/pull/1274)

**Comment by kendallstrautman** [comment]
[Updated docs](https://github.com/tinacms/tinacms.org/pull/478)

**Comment by kendallstrautman** [comment]
In testing this, I don't think the props are actually getting to the block component. We need to spread them within `InlineBlock`. Something like:

```diff
return (
  <InlineBlock
-  {...itemProps}
+  itemProps={itemProps}
    key={index}
    index={index}
    name={blockName}
    data={data}
    block={Block}
  />
)
```
```jsx
export interface InlineBlockProps {
  index: number
  name: string
  data: any
  block: Block
  itemProps?: {
    [key: string]: any
  }
}

export function InlineBlock({
  name,
  data,
  block,
  index,
  itemProps,
}: InlineBlockProps) {

  return (
    <InlineFieldContext.Provider value={{ name, ...block }}>
      <block.Component data={data} index={index} {...itemProps} />
    </InlineFieldContext.Provider>
  )
}
```

**Pull request merged**
