### PR TITLE
feat(react-tinacms-editor): Sidebar wysiwyg images, removes media popup

### PR DESCRIPTION
**Pull request by kendallstrautman**
Enables `imageProps` to be passed to the sidebar wysiwyg. Also removes the image popup from the menu entirely, so when you hit the media icon in the wysiwyg menu, the media manager opens immediately. 

Would love help testing this out to make sure it's all good and see if we actually like it better without the popup. If we want to keep the popup, we'll need to adjust some things in the sidebar.

### CODE REVIEW

**Comment by kendallstrautman** [comment]
There will be a merge conflict with #1554 but let's get that one in first since it fixes a higher priority issue

**Review by DirtyF — DISMISSED** [review]
I can insert images from the sidebar through the WYSIWYG image menu 👍

**Comment by dwalkr** [comment]
> There will be a merge conflict with #1554 but let's get that one in first since it fixes a higher priority issue

merged + resolved on this branch

**Review by dwalkr — APPROVED** [review]

**Pull request merged**
