### PR TITLE
feat: keyboard shortcut for toggle editor mode

### PR DESCRIPTION
**Pull request by jpuri**
Adding keyboard shortcut `Cmd-/` or `Ctrl-/` for mode toggling in editor.

### CODE REVIEW

**Review by DirtyF — COMMENTED** [review]
We need to change the shortcut as it's already taken under Chrome and Firefox (fire help)

Maybe `Option-CMD-/` ?

**Comment by jpuri** [comment]
I checked other editors and found that `Cmd-/` is mostly used to open help. For raw mode https://wordpress.org/gutenberg/ uses `alt-cmd-shift-M`. We can use check `alt-cmd-s` or `alt-cmd-t`.

**Comment by DirtyF** [comment]
Why not the letter M (for Markdown)?

**Comment by jpuri** [comment]
`alt-cmd-m`, `cmd-m` seems to be already used by chrome to  minimise window.

**Comment by DirtyF** [comment]
@jpuri yes that's why going with `alt-cmd-shift-M` seems to be the way to go with the letterr M.

**Comment by jpuri** [comment]
@DirtyF : PR is updated with use of key combination `alt-cmd-shift-M`.

**Review by DirtyF — APPROVED** [review]
This is so cool, thanks @jpuri

**Pull request merged**
