### PR TITLE
Feat/remove styled components dependencies

### PR DESCRIPTION
**Pull request by Phoenix-Alpha**
close ENG-590

### CODE REVIEW

**Comment by Phoenix-Alpha** [comment]
@jamespohalloran , can I add me as a contributor?

**Comment by jamespohalloran** [comment]
@all-contributors please add @Phoenix-Alpha for code, bug, and maintenance

**Review by logan-anderson — CHANGES_REQUESTED** [review]
@Phoenix-Alpha It looks like something is off with the notification for "Changes saved". See screenshot attached.
Screen Shot 2022-10-11 at 3 15 02 PM

**Comment by Phoenix-Alpha** [comment]
@logan-anderson , I fixed that issue. Please review again

**Review by jamespohalloran — APPROVED** [review]
Poked around on the starter with some different field and couldn't find any regressions!

**Comment by jeffsee55** [comment]
@Phoenix-Alpha this looks great to me! 

I'll defer to @spbyrne to give the final thumbs up before we merge

**Comment by spbyrne** [comment]
Looks great! 🎉

**Pull request merged**
