### PR TITLE
feat: Add the style attribute to the InlineBlocks component of the re…

### PR DESCRIPTION
**Pull request by Ryuurock**
…act-tinacms-inline package

### CODE REVIEW

**Comment by logan-anderson** [comment]
@Ryuurock  Sorry for the late reply, this code looks good to me I would love to see what @dwalkr thinks. 

On a side note it looks like you are using the Inline Editing API's. We have made the decision to mark these API's as experimental for the time being. [More detail can be found here](https://tina.io/blog/evolution-of-inline-editing/). We are currently recommending [using the sidebar with Tina Cloud](https://tina.io/guides/tina-cloud/starter/overview/) as the "Happy path".

That being set feel free to use the  Inline API's with this in mind 😄. Thanks for your contribution.

**Comment by DirtyF** [comment]
Why do we need inline styles here?

**Comment by dwalkr** [comment]
@Ryuurock could you [sign our Contributor License Agreement](https://cla-assistant.io/tinacms/tinacms?pullRequest=1953)? We require all contributors to sign it. It's OK if you prefer not to, but in that case we can't merge this PR.

**Comment by Ryuurock** [comment]
@dwalkr done

**Comment by Ryuurock** [comment]
> Why do we need inline styles here?

We have some styles that can be presented differently through configuration. In order not to deepen the div level, we directly use Container, but Container does not support style input

**Comment by dwalkr** [comment]
> @dwalkr done

unfortunately, it looks like the commit in this PR isn't associated with your GitHub account. This is a limitation of CLAAssistant; you can fix it by adding the email associated with this commit to your GH account: https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

**Comment by Ryuurock** [comment]
> > @dwalkr done
> 
> unfortunately, it looks like the commit in this PR isn't associated with your GitHub account. This is a limitation of CLAAssistant; you can fix it by adding the email associated with this commit to your GH account: https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

done 😊

**Review by dwalkr — APPROVED** [review]

**Comment by dwalkr** [comment]
@all-contributors add @Ryuurock for code

**Pull request merged**
