### PR TITLE
added autocomplete and more laguage supports for codeblock in rich-text

### PR DESCRIPTION
**Pull request by rabelais88**
this is a following up of https://github.com/tinacms/tinacms/discussions/3266#discussion-4458196

- added autocomplete component
- made codeblock in rich-text to support all languages registered in Monaco editor

### CODE REVIEW

**Comment by logan-anderson** [comment]
@rabelais88 Thanks for the contribution. I really like the idea of adding this. Looking at it, the placement of the autocomplete seems a bit off. Its in the top right and hidden behind the form (see screenshot). 
Screen Shot 2022-11-01 at 9 29 38 AM

**Comment by rabelais88** [comment]
> @rabelais88 Thanks for the contribution. I really like the idea of adding this. Looking at it, the placement of the autocomplete seems a bit off. Its in the top right and hidden behind the form (see screenshot). Screen Shot 2022-11-01 at 9 29 38 AM

@logan_anderson do you mean...
- the z-index of autocomplete is off?
- or shadow is not properly applied to all corners of autocomplete?
- or should autocomplete be placed on top-left? if this is the case, codeblock dropdown was placed on the same top-right position and and autocomplete component is respecting the original style.

it does not look off from the given screenshot, I didn't quite get the meaning. sorry for asking once again.

thank you for leaving a review!🙇‍♂️

**Comment by logan-anderson** [comment]
@rabelais88 My apologies the the issue I was seeing was with the autocomplete in the monaco editor and has nothing do to do with your PR. Everything looks good here to me.

**Review by logan-anderson — APPROVED** [review]
Looks good to me!

**Pull request merged**
