### PR TITLE
Adding support for image links

### LINKED ISSUE #694: Editor: link from an image
```gherkin
Given I have inserted an image
When I select the image
Then I can add a link
And expected markdown looks like:
```

```md
[![alt "title"](/images/example.png)](https://example.com "Go visit this link")
```

### PR DESCRIPTION
**Pull request by jpuri**
Adding support to link images.

Fix #694

### CODE REVIEW

**Comment by jpuri** [comment]
Support for links on images:

Screenshot 2020-02-17 at 3 25 54 PM

@spbyrne : the modal requires UX brushing.

**Comment by DirtyF** [comment]
Can't test it, getting a console error

**Comment by DirtyF** [comment]
Nice, it's functional, it could use a bit of polish.
 
- `Insert link` label instead of `Linked`,
-  keyboard: save modal on ENTER, cancel on ESC (as all other modals).

I can still use the link icon from the toolbar to insert a link, but the modal is not centered:

link_modal

When I click on the image again, then I get the unified modal, I'll let @spbyrne see if we should harmonize the behavior here.

**Comment by jpuri** [comment]
Hey @DirtyF :
I disabled link toolbar button when image is selected. This is how its working for me

Screenshot 2020-02-18 at 7 47 23 PM

Can you plz share a recording of link menu issue you are facing, so I will try to reproduce at my end.

**Comment by spbyrne** [comment]
Screen Shot 2020-02-18 at 10 52 31 AM

**Comment by DirtyF** [comment]
So now image is removed when hitting ENTER in the focus link modal 😥

**Comment by jpuri** [comment]
fixes #772

**Pull request merged**
