### PR TITLE
feat: update image settings

### PR DESCRIPTION
**Pull request by jpuri**
Adding option for user to change image settings.

@spbyrne : the modal to change image settings is currently very basic. Can you plz share your suggestions to style this.

Screenshot 2020-02-05 at 11 36 18 PM

Here is code: https://github.com/tinacms/tinacms/pull/720/files#diff-0393a673b5adcafe6cfbc512942efd31R55

### CODE REVIEW

**Comment by jpuri** [comment]
@spbyrne : I have done some improvements to modal positioning, it is not located at `bottom-center` of image. Please share your thoughts about positioning. I can change / improve that.

Modal content still needs to be styled here: https://github.com/tinacms/tinacms/pull/720/files#diff-0393a673b5adcafe6cfbc512942efd31R77.

Screenshot 2020-02-06 at 7 03 16 PM

**Comment by DirtyF** [comment]
When I have two images inserted, then modal of the second image, is positioned on the first one:

image-settings-modal

**Comment by jpuri** [comment]
Hey @DirtyF : I fixed the issue with multiple image modals.

**Comment by DirtyF** [comment]
It looks like the styles messed up the previous behavior which was fine.

**Comment by spbyrne** [comment]
I'll take a look, @DirtyF 

I may have overwritten something key to that fix.

**Comment by DirtyF** [comment]
Positioning is all over the place with sticky toolbar and modals: https://www.loom.com/share/069d12fc335a4922a391aa97c0eae6f3

**Comment by DirtyF** [comment]
This was merged, but isn't done:
 - clicking save on the settings modal does not close the modal (as it does for the link modal)
 - when updating alt or title on an image, it saves properties for all images
 - modal positioning  (on scroll sometimes modal get resized)

modal-scroll-safari-13


  - nice to have: auto-scroll to an image on select (when I do click on top of an image, scroll down to the modal so that I can type)

**Pull request merged**
