### PR TITLE
Menu refactor

### PR DESCRIPTION
**Pull request by jpuri**
Menu refactoring WIP.

### CODE REVIEW

**Comment by jpuri** [comment]
Hey @spbyrne : can you plz check sticky behaviour of menubar in this PR, I am doubtful that I broke something.

Can you also check toggling between wysiwyg and markdown mode and see if menu works well.

**Comment by spbyrne** [comment]
Looks like the regular menu still sticks correctly but the new menu doesn't. I'll troubleshoot.

**Comment by spbyrne** [comment]
Good to go now.

**Comment by DirtyF** [comment]
Great work, that sticky position is still hard to get right, given you can have inline image blocks before, etc.

https://www.loom.com/share/fa6a9b3c6cb14db38eb1c1f8be6a7539

**Comment by jpuri** [comment]
Hey @DirtyF : it looks like issue is that changing mode is resetting the scroll and changing focus.
Can you plz confirm ?

**Comment by jpuri** [comment]
PR refactors menubar, internally editor has 2 separate menubars for prosemirror / markdown modes.

For plugins, single react component `MenuItem` will be used for rendering menu in all modes. 
Check [here](https://github.com/tinacms/tinacms/pull/1217/files#diff-9d3572f8ceed23f7f5b108bfe3c520d3R119). It will be passed as parameter `mode` (`wysiwyg` or `markdown`) and prosemirror `editorView`.

cc @ncphillips 

I am creating a separate issue for scroll reset when changing modes. cc @DirtyF

**Comment by jpuri** [comment]
Issue to fix scrolling when changing mode: https://github.com/tinacms/tinacms/issues/1225

**Pull request merged**
