### PR TITLE
Chrome Components

### PR DESCRIPTION
**Pull request by spbyrne**
Working on chrome updates based on work from prototype. Not to merge until after initial `inject-tailwind` branch is released. 

Screen Shot 2022-01-14 at 3 51 13 PM

Screen Shot 2022-01-14 at 3 52 39 PM

### CODE REVIEW

**Comment by Enigmatical** [comment]
Took a quick video of our progress so far with this:
https://www.loom.com/share/7f8c3918b2b3467189394d1d2dfbcca6

As cool as the pictures are, seeing it in motion is where I think it really shines. 🎉

**Comment by Enigmatical** [comment]
* [ ] Hide "Document Creator" in Navigation _if_ `tina-admin` flag is `true`

**Comment by logan-anderson** [comment]
Looks good to me. When ever you want to merge it I will approve it

**Review by logan-anderson — APPROVED** [review]
🎉

**Pull request merged**
