### PR TITLE
Table: Safari fix and alignment

### LINKED ISSUE #702: Table: Safari compatibility
Two main issues at the moment: 

- HItting arrow keys when a row or a column is selected
- Add icon should disappear after insertion

Illustrated in this video: https://www.loom.com/share/ad259d9994de47b79f84c72effbb7e00

### PR DESCRIPTION
**Pull request by DirtyF**
Fix #702

### CODE REVIEW

**Comment by jpuri** [comment]
Screenshot 2020-01-30 at 7 37 05 PM

PR has changes for table alignment also, @spbyrne : can you plz style icons.

closes: https://github.com/tinacms/tinacms/issues/641

closes: https://github.com/tinacms/tinacms/issues/593

**Comment by DirtyF** [comment]
About alignment: 
- You should be able to align only when you select a column
- Given you have a centered column, when you add a new row, then the text in the cell should be centered (same for other aligned cells)

**Comment by ncphillips** [comment]
I would add that the current alignment has an "active" state

Question about @DirtyF's first point. How should that be handled? I have two ideas in mind:
1. they're not visible
1. they are still visible but they are disabled

**Comment by ncphillips** [comment]
What does @spbyrne

**Comment by DirtyF** [comment]
@ncphillips I'd go with the first solution, alignment Icons are not visible unless you select one or more table columns. UI should only be displayed when relevant.

**Comment by ncphillips** [comment]
There was a linting error:

```

/home/runner/work/tinacms/tinacms/packages/@tinacms/fields/src/Wysiwyg/commands/heading-commands.ts
##[error]  19:23  error  'Selection' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

**Comment by DirtyF** [comment]
@jpuri feel free to approve, I did open the PR ;)

**Pull request merged**
