### PR TITLE
Run CI checks on supported node versions 

### PR DESCRIPTION
**Pull request by jamespohalloran**
Test build on node 16 & 17.
Should pass once #2221 is merged

fixes #2412

### CODE REVIEW

**Review by logan-anderson — DISMISSED** [review]
Looks good to me!

A side note:
 the `e2e` tests will probably fail until  https://github.com/tinacms/tinacms/pull/2261 is merged.

**Comment by jamespohalloran** [comment]
Just noticed that this action is only run after it's been merged to main. Should the "main" action run on PR (and also on push)? @jeffsee55

**Comment by jamespohalloran** [comment]
I combined the `build-test-lint.yml` & `main.yml` actions into one, so that we'll build against all node-versions on PRs (let me know if you disagree on doing so. 
Also, this should probably want for https://github.com/tinacms/tinacms/pull/2221 to be merged so we don't fail every build.

**Comment by jamespohalloran** [comment]
I'm pretty sure the failing tests are from the tailwind merge: https://github.com/tinacms/tinacms/actions/runs/1713882786

**Review by jeffsee55 — APPROVED** [review]

**Pull request merged**
