### PR TITLE
Adding table delete option.

### PR DESCRIPTION
**Pull request by jpuri**
Delete table option:

Screenshot 2020-01-29 at 4 04 42 PM

### CODE REVIEW

**Comment by DirtyF** [comment]
How do we selection the table before deleting?

Paper a a top left icon to click, then table is marked as selected then you can click the delete icon
table-select-delete

What do you think @jpuri ?

**Comment by DirtyF** [comment]
@jpuri oh sorry I saved and it pushed the commit, do you want me to revert it?

**Comment by jpuri** [comment]
Fixes: https://github.com/tinacms/tinacms/issues/631

**Comment by jpuri** [comment]
Closes: https://github.com/tinacms/tinacms/issues/631

**Pull request merged**
