### PR TITLE
Line numbers

### PR DESCRIPTION
**Pull request by jamespohalloran**
Add Line number to raw editor. 
Also make the error UI on the right-hand-side more visible

Screen Shot 2023-01-26 at 10 53 16 AM

### CODE REVIEW

**Comment by jeffsee55** [comment]
This is taking up a lot of space on the left, maybe we can remove some padding?

**Comment by jamespohalloran** [comment]
> This is taking up a lot of space on the left, maybe we can remove some padding?



> This is taking up a lot of space on the left, maybe we can remove some padding?

Are we applying any custom styling to the monaco editor yet? I'm not sure where that's configured.

**Comment by jeffsee55** [comment]
I think it'd just work to add a `<style>` tag somewhere targetting it, not a big deal if it's not trivial though.

**Comment by jamespohalloran** [comment]
> I think it'd just work to add a `<style>` tag somewhere targetting it, not a big deal if it's not trivial though.

Fixed!
Screen Shot 2023-01-26 at 10 23 59 AM

**Comment by jamespohalloran** [comment]
Also pushed up a change to make the error-UI on the right-hand side wider

**Review by jeffsee55 — APPROVED** [review]

**Pull request merged**
