### PR TITLE
Custom empty state

### PR DESCRIPTION
**Pull request by kendallstrautman**
[Original PR](https://github.com/tinacms/tinacms/pull/1242) by @DaniTulp 

_Notes from Original:_

Addresses #228. I'm not completely sure about the naming of the prop. I've added an example to the demo-next example, if you go to the blocks page you can see it renders it correctly.

### CODE REVIEW

**Comment by ncphillips** [comment]
Looks good! I have a couple nit-picky comments around naming and default values but I'll post those tomorrow morning.

**Comment by DaniTulp** [comment]
I'll wait on the nitpicks before adding a pull-request for the docs.

**Comment by ncphillips** [comment]
Thanks for the patience! Here's my thoughts:

I think defaulting to `NoFormsPlaceholder` should be done in `SidebarState` instead of in the `FormsView`. The `FormView` will just not render anything if there's no `CustomEmptyState`. That means the `emptyState` will be still be optional when creating, but the default component will be `NoFormsPlaceholder`:

```ts
  constructor(private events: EventBus, options: SidebarStateOptions = {}) {
    this.position = options.position || 'displace'
    this._hidden = !!options.hidden
    this.emptyState = options.emptyState || NoFormsPlaceholder
```

That said, I'm also not big on the names `emptyState` and `CustomEmptyState`. They're a bit misleading as the usual meaning of "state" in React is about data not components.

I'm not really sure what I think that should be called, but an idea I have is `sidebar.body`. Instead of passing the component as a prop:

```jsx
<FormsView CustomEmptyState={sidebar.body} />
```

The component could then be the child:

```jsx
<FormsView>
  <sidebar.body />
</FormsView>
```

I like that but not totally sold on it, so other thoughts are welcomed!

**Comment by DaniTulp** [comment]
I definitely agree with pulling out the empty component outside of the `<FormsView>` and into the Sidebar component. 

Where should the `NoFormsPlaceHolder` component live? Its own file?

Naming these things is indeed pretty hard, `emptySidebarBody` comes to mind or `emptySidebar` I feel like having the word empty in it does add some significance. Another option could be to mirror the `NoFormsPlaceholder` component as a prop.

**Comment by ncphillips** [comment]
> Where should the NoFormsPlaceHolder component live? Its own file?

Yeah I think so. In it's own file. Exact place in package matters a bit less.

>  I feel like having the word empty in it does add some significance.

Yeah that's a good point. I don't think the `sidebar` is required in the name, since it's placed on the component. What about `sidebar.emptyBody` or `sidebar.placeholder`?

```jsx
<FormsView>
  <sidebar.emptyBody />
</FormsView>
```

or

```jsx
<FormsView>
  <sidebar.placeholder />
</FormsView>
```

**Comment by DaniTulp** [comment]
I'm nudging towards placeholder for consistency with the default option.

**Comment by ncphillips** [comment]
Cool. Agreed 👍

**Pull request merged**
