### PR TITLE
Feat/media store s3

### PR DESCRIPTION
**Pull request by Phoenix-Alpha**

### CODE REVIEW

**Comment by jeffsee55** [comment]
I ran into a couple issues getting this running:

- First the build wasn't able to find `@aws-sdk/signature-v4-crt`, it looks like that's a peer dep on [`@aws-sdk/signature-v4-multi-region`](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/signature-v4-multi-region/package.json#L44). 
- After adding that as a dependency I ran into this error: 
  ```
  warn  - ../../node_modules/.pnpm/aws-crt@1.14.1/node_modules/aws-crt/dist/native/binding.js
  Critical dependency: the request of a dependency is an expression
  (node:66552) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
  ```

**Comment by Phoenix-Alpha** [comment]
@jeffsee55, Can you send me the full error log?

**Comment by Phoenix-Alpha** [comment]
@jeffsee55 ,
Do you still have the issue with running?

**Comment by jeffsee55** [comment]
@Phoenix-Alpha yes I'm still seeing this issue, here's the full log:

```
warn  - ../../node_modules/.pnpm/@aws-sdk+signature-v4-multi-region@3.130.0/node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/SignatureV4MultiRegion.js
Module not found: Can't resolve '@aws-sdk/signature-v4-crt' in '/Users/jeffsee/code/tinacms2/node_modules/.pnpm/@aws-sdk+signature-v4-multi-region@3.130.0/node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs'

../../node_modules/.pnpm/@aws-sdk+util-user-agent-node@3.127.0/node_modules/@aws-sdk/util-user-agent-node/dist-cjs/is-crt-available.js
Module not found: Can't resolve 'aws-crt' in '/Users/jeffsee/code/tinacms2/node_modules/.pnpm/@aws-sdk+util-user-agent-node@3.127.0/node_modules/@aws-sdk/util-user-agent-node/dist-cjs'
(node:59076) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by jeffsee55** [comment]
This is happening from within the monorepo, here's my branch: https://github.com/tinacms/tinacms/compare/test-media-store-s3?expand=1

**Comment by Phoenix-Alpha** [comment]
Could you test on tina-cloud-starter using this pack? @jeffsee55 
[tina-cloud-starter.zip](https://github.com/tinacms/tinacms/files/9462748/tina-cloud-starter.zip)

**Comment by jeffsee55** [comment]
We'll need this to work for pnpm as well as yarn (which is what the starter uses). I expect we need to add a dependency that's missing from an S3 library.

**Comment by Phoenix-Alpha** [comment]
Would you push your code used to test DO Space?

**Comment by Phoenix-Alpha** [comment]
@jeffsee55 , I think we can test the s3 integration locally with tina-cloud-starter(the independent repository).
Reference: https://dev.to/scooperdev/use-npm-pack-to-test-your-packages-locally-486e

**Comment by Phoenix-Alpha** [comment]
@jeffsee55 , I added `@aws-sdk/signature-v4-crt` as a devDependency and it worked. Plz check https://github.com/tinacms/tinacms/compare/feat/media-store-s3...test-media-store-s3?expand=1

**Comment by jeffsee55** [comment]
> devDependency and it worked

I think this will need to be a `dependency`. It might work in the monorepo because `devDependencies` are present, but those wouldn't get installed, whereas `dependencies` would.

**Comment by Phoenix-Alpha** [comment]
@jeffsee55  I changed it to a dependency from devDependency and it still works well. Please confirm.

**Comment by jeffsee55** [comment]
@Phoenix-Alpha did you push those changes to this branch?

**Comment by Phoenix-Alpha** [comment]
> @Phoenix-Alpha did you push those changes to this branch?
@jeffsee55, I pushed to this branch - https://github.com/tinacms/tinacms/tree/test-media-store-s3

**Comment by jeffsee55** [comment]
This is working for me now, thanks @Phoenix-Alpha! I've updated on this branch so will just merge in once CI passes

**Review by jeffsee55 — APPROVED** [review]

**Pull request merged**
