### PR TITLE
Add basePath prefix to files in media manager

### PR DESCRIPTION
**Pull request by Albert-Mv**
In addition to [this](https://github.com/tinacms/tinacms/pull/3911) PR I made some changes to media manager to add basePath support.

Before these changes files were loaded in the media manager without the basePath prefix. Links to images were incorrect.
Now, if we have basePath, links will have prefix.

### CODE REVIEW

**Comment by logan-anderson** [comment]
@Albert-Mv what is the difference between this and `mediaRoot`?

**Review by jamespohalloran — APPROVED** [review]

**Review by logan-anderson — CHANGES_REQUESTED** [review]
@Albert-Mv They way this is working right now it will not work in production. 

See this video for a bit more context:  https://www.loom.com/share/d17dc35ef23743ac877761a149987948

We are happy to take it over from here since it will be a bit harder to test. But if you want to take it on, your more then welcome.

**Comment by Albert-Mv** [comment]
@logan-anderson thank you for the feedback. I got it, I'll modify this two functions to add Tina Cloud url support

**Comment by Albert-Mv** [comment]
> @Albert-Mv They way this is working right now it will not work in production.
> 
> See this video for a bit more context: https://www.loom.com/share/d17dc35ef23743ac877761a149987948
> 
> We are happy to take it over from here since it will be a bit harder to test. But if you want to take it on, your more then welcome.

Could you please help me a bit: I can't understand how did you run admin panel on localhost in production mode (I don't see the alert "You are currently in Local mode")

**Comment by logan-anderson** [comment]
@Albert-Mv its a bit award right now but the best way is to create a new Tina Cloud project with the tina-cloud-starter. Set that up in app.tina.io and then add the token, clientId and branch to the examples/tina-cloud-starter in the mono repo. 

Then you can run `pnpm build` and `pnpm start`. 

However for testing this feature in particular the site has to use `basePath`. You may have to setup some nextjs redirects to ensure that works.

**Pull request closed without merging**
