### PR TITLE
Update final-form-builder.tsx styled component

### PR DESCRIPTION
**Pull request by Spraynard**
Removing `white-space: nowrap` from FieldsGroup div styling

Saw #476 and figured I could tackle that issue.

Seemed to just involve removing the `white-space` directive to go back to a `normal` default.

My guess is that this was added in order to have titles themselves not wrap? If so, that functionality is probably gone as well, but I don't know if it's a breaking change to go from no-wrap to wrap.

Here's a screenshot of the change on the gatsby demo:

Screen Shot 2019-11-21 at 3 30 26 PM

### CODE REVIEW

**Comment by spbyrne** [comment]
Awesome work @Spraynard, thanks! I'll take a look at this tomorrow morning :smile:

**Comment by Spraynard** [comment]
Thank you :)

**Comment by spbyrne** [comment]
We had a discussion at one point around text wrapping. For labels it was intentional that they don't wrap; we have `text-overflow: ellipsis;` on the label element. I think if we want to support text wrapping specifically for the description, we could put `white-space: normal;` on the `FieldDescription` component in `packages/tinacms/src/plugins/fields/wrapFieldWithMeta.tsx` and leave the `final-form-builder.tsx` white-space definition as-is.

**Comment by spbyrne** [comment]
Screen Shot 2019-11-22 at 11 12 07 AM

**Comment by Spraynard** [comment]
Alright I think that we're all good now. I've updated `wrapFieldWithMeta.tsx` `FieldDescription` component styling to have `white-space: normal` defined.

From the looks of it, the layout that I'm getting is the same as what you were requesting. Example below.

tina-cms-resolution

Thank you very much for the guidance.

**Comment by spbyrne** [comment]
Thanks @Spraynard !

**Comment by spbyrne** [comment]
@all-contributors please add @Spraynard for code

**Pull request merged**
