### PR TITLE
feat(rollup) Add ts plugin for better style components experience

### PR DESCRIPTION
**Pull request by ncphillips**
Original PR by @maciekgrzybek 

- install and add typescript-plugin-styled-components to the rollup config
- plugins creates better developer experience by adding meaningful class names

### CODE REVIEW

**Comment by spbyrne** [comment]
This will be great. Major improvement for debugging styles.

**Comment by ncphillips** [comment]
ermagerrd this is so much better

image

@all-contributors please add @maciekgrzybek for builds

**Comment by ncphillips** [comment]
@all-contributors please add @maciekgrzybek for build

**Comment by ncphillips** [comment]
apparently that's not a thing

@all-contributors please add @maciekgrzybek for infra

**Pull request merged**
