### PR TITLE
chore(ci): test Node LTS active releases

### LINKED ISSUE #1355: Document node versions with "engine" field
## Summary

You can get build errors if you don't use the right node version. NPM/Yarn can warn on this if it's specified in package.json.

https://docs.npmjs.com/files/package.json#engines

### Basic example

N/A
### Motivation

Reduce any need for support related to this issue.

### What we know

| Node Version | Works |
| --- | --- |
| v10.18.1| ✅ |
| v12.16.1 | ✅ |
| v12.18.3 |  ✅|

### PR DESCRIPTION
**Pull request by DirtyF**
Fix #1355

Documentation: https://docs.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions#specifying-the-nodejs-version

- [x] Add status badge to README ([doc](https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository))

_Note: Badge can be created from the [action workflow page](https://github.com/tinacms/tinacms/actions?query=workflow%3A%22Build%2C+Test%2C+Lint%22) and will display the name of the workflow._

Default badge

Build, Test, Lint for Master

### CODE REVIEW

**Comment by DirtyF** [comment]
Note: The node 10.x / macOS script took more than 30min to complete, we might not want to run the whole matrix the whole time.

**Comment by ncphillips** [comment]
Yeah, I think I'd like to get get the full matrix only running on `master` and then have only `ubuntu` with one version of node running on all other branches

**Comment by DirtyF** [comment]
@chrisdmacrae There's a already separate file for PRs, the scope of this PR is to run all active Node version on master.

**Comment by chrisdmacrae** [comment]
> @chrisdmacrae There's a already separate file for PRs, the scope of this PR is to run all active Node versions on master.

@DirtyF gotcha. In that case, this looks right to me. On master, we run all node versions. On PRs, we just run LTS.

**Pull request merged**
