### PR TITLE
build(react-tinacms-github): moved from tsdx to tina-scripts and adde…

### PR DESCRIPTION
**Pull request by chrisdmacrae**
…d missing type annotations

This PR removes tsdx from `react-tinacms-inline` and adds missing type annotations to fix build errors.

### CODE REVIEW

**Comment by ncphillips** [comment]
Looks like Tina scripts needs to be added to dev deps

**Comment by chrisdmacrae** [comment]
@ncphillips any idea what's going on in the build?

**Comment by ncphillips** [comment]
Gotta change main or whatever. Probably looking at `build`

**Comment by chrisdmacrae** [comment]
> Gotta change main or whatever. Probably looking at `build`

TSDX had `main` and `module`, Tina scripts doesn't have `module`.

Also Tina scripts outputs `typings` to `dist/src/index.d.ts` instead of `dist/index.d.ts`

**Comment by chrisdmacrae** [comment]
This is good to go @tinacms/maintainers

**Pull request merged**
