### PR TITLE
Fix issue where link form does not render.

### LINKED ISSUE #4369: Link button pressed in wysiwyg returns an error
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

[Screencast from 27-11-2023 12:35:22 ΜΜ.webm](https://github.com/tinacms/tinacms/assets/2639571/1039602a-53b8-44a1-b1c6-7c7b760e7253)

Rendering breaks when **insert link** button is pressed in wysiwyg editor. Returns "error in `<FormBuilder>` component".

- Note: This only happens when the link button is pressed in wysiwyg. The rendered md / mdx links are working fine. Everything else works fine.

- Confirmed in 4 recently updated browsers on  localhost 3000 on  a new machine.
- Confirmed also in netx-tinacms barebones repo after updating `@tinacms/cli` to `^1.5.34`

- Local cli reports no errors:

Screenshot from 2023-11-24 17-47-58

- Dev-tools are reporting the following :

Screenshot from 2023-11-24 17-35-26

- When the link button is pressed, admin returns the following error in the gui:

Screenshot from 2023-11-24 17-42-31

- Deployed on Netlify have the same problem

### Reproduction

https://github.com/tinacms/tina-barebones-starter

### Steps to reproduce

_No response_

### System Info

```shell
- System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700K
    Memory: 57.13 GB / 62.62 GB
    Container: Yes
- Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
- Browsers:
    Brave Browser: 119.1.60.118
    Chrome: 119.0.6045.159
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

### PR DESCRIPTION
**Pull request by logan-anderson**
fixes #4369

### CODE REVIEW

**Comment by kldavis4** [comment]
@logan-anderson what's the root cause of #4369

**Comment by logan-anderson** [comment]
> @logan-anderson what's the root cause of #4369

The forms relativePath was not getting set correctly (it was getting set to the randomly generated ID) and [this line of code ](https://github.com/tinacms/tinacms/blob/afd1c7c97d50cf7a4a228dd1b82dbe4241f14349/packages/tinacms/src/toolkit/form-builder/form-builder.tsx#L117)was failing.

**Comment by kldavis4** [comment]
> > @logan-anderson what's the root cause of #4369
> 
> The forms relativePath was not getting set correctly (it was getting set to the randomly generated ID) and [this line of code ](https://github.com/tinacms/tinacms/blob/afd1c7c97d50cf7a4a228dd1b82dbe4241f14349/packages/tinacms/src/toolkit/form-builder/form-builder.tsx#L117)was failing.

thanks - that line of code was part of the fix for the broken saved state change indicator. Are there any other places where the relativePath might be getting set incorrectly that would trigger this?

**Comment by logan-anderson** [comment]
> > > @logan-anderson what's the root cause of #4369
> > 
> > 
> > The forms relativePath was not getting set correctly (it was getting set to the randomly generated ID) and [this line of code ](https://github.com/tinacms/tinacms/blob/afd1c7c97d50cf7a4a228dd1b82dbe4241f14349/packages/tinacms/src/toolkit/form-builder/form-builder.tsx#L117)was failing.
> 
> thanks - that line of code was part of the fix for the broken saved state change indicator. Are there any other places where the relativePath might be getting set incorrectly that would trigger this?

I could not find any. 

I tested
- images (Both in a markdown file and standalone)
- MDX Templates
- Object fields

**Comment by logan-anderson** [comment]
Looking at the code `FormModal` may also be effected. Let me take a look

**Review by kldavis4 — APPROVED** [review]

**Pull request merged**
