### PR TITLE
fixed media bundle

### PR DESCRIPTION
**Pull request by logan-anderson**
Fixes https://github.com/tinacms/tinacms/issues/2035

### CODE REVIEW

**Comment by logan-anderson** [comment]
Not getting this build error locally any ideas @jeffsee55 ?

**Comment by jeffsee55** [comment]
@logan-anderson just to make sure are you actually running `yarn types` locally? The build is separate from the type build now

**Comment by logan-anderson** [comment]
@jeffsee55 Yup that was it! Thanks

**Review by DirtyF — APPROVED** [review]
Niiiice

**Pull request merged**
