### PR TITLE
fix(react-tinacms-github): fix missing unique "key" prop in modal actions

### LINKED ISSUE #1557: ActionableModal .map function missing `key` prop
The `ActionableModal` component in the react-tinacms-github package is missing a `key` prop on the `actions.map` method, raising an unnecessary `Warning: Each child in a list should have a unique "key" prop.` warning.

### PR DESCRIPTION
**Pull request by travismiller**
Fix missing unique "key" prop in modal actions.

Also replace deprecated ModalPopup with PopupModal.

Closes #1557

### CODE REVIEW

**Comment by DirtyF** [comment]
@travismiller Could you please [sign our CLA](https://cla-assistant.io/tinacms/tinacms?pullRequest=1744)?

**Comment by travismiller** [comment]
Oh, thought I had. Seems I have now!

**Review by DirtyF — APPROVED** [review]
LGTM thanks @travismiller 🙏

**Comment by dwalkr** [comment]
@all-contributors add @travismiller for code

**Pull request merged**
