### PR TITLE
Fix not warning unsaved issue

### PR DESCRIPTION
**Pull request by Phoenix-Alpha**

### CODE REVIEW

**Comment by Phoenix-Alpha** [comment]
Fix #2766

**Comment by jamespohalloran** [comment]
Hey! So this looks like the type of thing we're looking for, but the ticket was moreso for the forms of existing documents. This looks like the code that used to prevent navigating away from a dirty document: https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/toolkit/src/packages/form-builder/FormBuilder.tsx#L90-L93

However at some point, it seems it stopped working

**Comment by Phoenix-Alpha** [comment]
@jamespohalloran , `onBeforeUnload` is called when the document is unloaded and navigated to another document.
And the issue is `onBeforeUnload` is not called when route navigation in React SPA.

**Comment by Phoenix-Alpha** [comment]
To prevent react route navigation, we used to use `usePrompt` hook of `react-router-dom` but it was removed from `react-router-dom` v6 so I defined custom `usePrompt` hook

**Comment by jeffsee55** [comment]
Isn't this supposed to work on edit forms (both contextual and in the admin)?

In general, the iframe stuff uses the same code as current contextual forms. But this won't work regardless for that because there is no window location change.

**Comment by jamespohalloran** [comment]
> Isn't this supposed to work on edit forms (both contextual and in the admin)?

That was the original intent yeah. I was wondering if this could live inside the useTina hook (so the location change would be inside the iframe), but I guess if I'm understanding correctly, that wouldn't work because it wouldn't have the react-router scope?

**Comment by jeffsee55** [comment]
> I was wondering if this could live inside the useTina hook (so the location change would be inside the iframe)

It might be doable but yeah it'll be totally different logic because the `useTina` hook might represent multiple forms.

**Comment by jamespohalloran** [comment]
Just converted this one to a draft. My fault for pulling into the "ready to be worked on issues", but I think it might just need some more discussion based on the thread.

**Comment by Phoenix-Alpha** [comment]
@all-contributions please add @Phoenix-Alpha for its contribution to doc, code and plugin.

**Comment by jeffsee55** [comment]
Closing as I think we'll need a pretty different approach for this, feel free to reopen if necessary

**Pull request closed without merging**
