### PR TITLE
Clearable Images

### PR DESCRIPTION
**Pull request by jamespohalloran**
Improvement for: https://github.com/tinacms/tinacms/issues/190

Add a delete button to the image-upload. 
Also fixed the upload directory in the demo project, and made its parse handle a clearable image.

TODO: 
- [x] Clearable should be an option
- [x] Needs some style love

### CODE REVIEW

**Comment by jamespohalloran** [comment]
@spbyrne No rush on this, but could you give this a styling looksee whenever you get a chance?
I just ripped the trash icon styling from the groups field.
Screen Shot 2019-10-18 at 4 44 20 PM

**Comment by spbyrne** [comment]
I tweaked the styles on the delete button & image hover.

**Comment by ncphillips** [comment]
Will this just be an improvement, or will it actually fix #190?

**Comment by jamespohalloran** [comment]
> I tweaked the styles on the delete button & image hover.

Thanks! Looks great!

**Comment by jamespohalloran** [comment]
> Will this just be an improvement, or will it actually fix #190?

IMO it's an improvement & not a fix since https://github.com/tinacms/tinacms/issues/190 isn't a bug, but yeah it will address that issue.

**Comment by patrickconroy** [comment]
Hello everyone. Sorry if I'm going crazy, but with 0.32.0 there's no trash button for the image component. I'd consider this a bug because if you upload an image it's stuck there. The only fix is to upload a transparent image in its place.

**Comment by DirtyF** [comment]
@patrickconroy We just released 0.33.0 which fixes a bug related to clearing images from the sidebar. Does it solve your issue?

**Pull request merged**
