### PR TITLE
chore: fix lodash deps

### PR DESCRIPTION
**Pull request by ncphillips**
Noticed some warnings coming from danger. Fixed up a couple imports.

- [ ] Test this change. (I didn't even see if it would build before pushing 😅)

### CODE REVIEW

**Comment by DirtyF** [comment]
@ncphillips getting an error on this branch when trying to build @tinacms/fields package:

```
lerna ERR! npm run build stderr:
/Users/frank/tina/tinacms/packages/@tinacms/scripts/bin/scripts.js:33
  throw err
  ^

Error: /Users/frank/tina/tinacms/packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/ImageMenu/index.tsx(21,22): semantic error TS7016: Could not find a declaration file for module 'lodash.debounce'. '/Users/frank/tina/tinacms/node_modules/lodash.debounce/index.js' implicitly has an 'any' type.
  Try `npm install @types/lodash.debounce` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash.debounce';`
```

**Comment by ncphillips** [comment]
I’m sorry to ask, but did you run `npm run bs`?

**Comment by jpuri** [comment]
Thanks for adding that dependency @ncphillips , I missed that one.

**Comment by DirtyF** [comment]
@ncphillips 🤦‍♂

**Pull request merged**
