### PR TITLE
Fix empty selections issue

### LINKED ISSUE #3246: Generated frags.gql missing body
## Description

I honestly haven't dug into this error much yet, so I haven't figured out the actual cause, but I'm getting this error on my personal site.

### Steps to reproduce

1. Check out PR for my personal site [here](https://github.com/mAAdhaTTah/frontend/pull/739)
2. `nvm use 14 && npm ci && npx tinacms build`
3. See error

### Expected result

Builds correctly.

### Actual result

```
  Syntax Error: Expected "{", found "}".

~/frontend/.tina/__generated__/frags.gql:483:19
482 |                     ... on PageLandingBodyResumeEmbed
483 |                   }
    |                   ^
484 |                 }
GraphQLError: Syntax Error: Expected "{", found "}".
    at syntaxError (~/frontend/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.expectToken (~/frontend/node_modules/graphql/language/parser.js:1413:40)
    at Parser.many (~/frontend/node_modules/graphql/language/parser.js:1519:10)
    at Parser.parseSelectionSet (~/frontend/node_modules/graphql/language/parser.js:271:24)
    at Parser.parseFragment (~/frontend/node_modules/graphql/language/parser.js:379:26)
    at Parser.parseSelection (~/frontend/node_modules/graphql/language/parser.js:284:58)
    at Parser.many (~/frontend/node_modules/graphql/language/parser.js:1523:26)
    at Parser.parseSelectionSet (~/frontend/node_modules/graphql/language/parser.js:271:24)
    at Parser.parseField (~/frontend/node_modules/graphql/language/parser.js:312:68)
    at Parser.parseSelection (~/frontend/node_modules/graphql/language/parser.js:284:81)
```

Looks like the `frags.gql` doesn't build correctly.

#### Tinacms Package Versions

```text
├─┬ @tinacms/cli@0.61.20
│ ├─┬ @tinacms/app@0.0.19
│ │ ├─┬ @tinacms/scripts@0.51.1
│ ├─┬ @tinacms/datalayer@0.2.4
│ ├─┬ @tinacms/graphql@0.63.12
│ │ ├─┬ @tinacms/mdx@0.61.10
│ ├─┬ @tinacms/metrics@0.0.3
│ ├─┬ @tinacms/schema-tools@0.1.6
├─┬ react-tinacms-editor@0.53.26
│ ├─┬ @tinacms/toolkit@0.56.34
│ │ ├── @tinacms/sharedctx@0.1.1
├─┬ tinacms@0.69.14
│ ├── @tinacms/sharedctx@0.1.3
│ ├─┬ @tinacms/toolkit@0.57.10
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |     OSX    |
| node    |      14.17.6   |
| npm     |     6.14.15    |

### PR DESCRIPTION
**Pull request by Phoenix-Alpha**
Fix #3246
Closes ENG-597

### CODE REVIEW

**Comment by logan-anderson** [comment]
@Phoenix-Alpha Can you add a changset? (Other than that it looks good)

**Comment by mAAdhaTTah** [comment]
One thing I'll flag is that in the original issue, the `PageLandingBodyResumeEmbed` is a template with a single reference field, so it shouldn't generate an empty body.

**Comment by Phoenix-Alpha** [comment]
> One thing I'll flag is that in the original issue, the `PageLandingBodyResumeEmbed` is a template with a single reference field, so it shouldn't generate an empty body. I updated the original issue with that template.

Replied in the [original issue](https://github.com/tinacms/tinacms/issues/3246)

**Comment by mAAdhaTTah** [comment]
Not to be a pest, but any chance we could get this merged? I think I'm gonna keep my schema the same so I need this to get everything working.

**Comment by jeffsee55** [comment]
@mAAdhaTTah just merged it. The team is on a short break but this should be available on the @beta tag in a few minutes if that's ok. We will release next week.

**Comment by mAAdhaTTah** [comment]
@jeffsee55 Super appreciated, thank you!

**Pull request merged**
