### PR TITLE
fix: use the db status endpoint for checking credentials

### PR DESCRIPTION
**Pull request by kldavis4**
Instead of making a graphql query to validate token/clientId/branch, switch to the checking the db status endpoint. This should fix an issue where, when a new branch is created and indexing is still in progress, the query used in checkClientInformation fails because the index hasn't been created yet. This was happening before the waitForDb check and  resulting in Vercel build failures.

### CODE REVIEW

**Review by jamespohalloran — DISMISSED** [review]
Awesome!

**Comment by jamespohalloran** [comment]
Testing this out in a PR deploy and found a few things:
The spinner logic we use doesn't really work well in CI:
Screen Shot 2023-01-20 at 9 23 00 AM

**Comment by jeffsee55** [comment]
> The spinner logic we use doesn't really work well in CI:

We can probably check for `process.env.CI` before showing those types of animations.

**Comment by jamespohalloran** [comment]
> > The spinner logic we use doesn't really work well in CI:
> 
> We can probably check for `process.env.CI` before showing those types of animations.

Just made that fix!

**Review by jamespohalloran — APPROVED** [review]

**Pull request merged**
