### PR TITLE
Tinacms ui

### PR DESCRIPTION
**Pull request by ncphillips**
`tinacms-ui` is a [Stencil](https://stenciljs.com/docs/introduction) component package

When `tinacms-ui` is built, it generates typescript source files in the `@tinacms/styles` package. These generated files declare fully-typed React bindings for the components defined in `tinacms-ui`. The `@tinacms/styles` package them re-exports them for use in React applications.

I am not particularly fond of this structure, but it's a start. 

The most interesting things to look at are:

1. `my-component.tsx`: The Stencil component
1. `my-component.css`: The style-sheet for the component. Note that this is completely isolated via shadow dom. 
1. `stencil.config.js`: Configures how the React adapters get generated.
1. `FormView.tsx`: Shows an example of using the Stencil component inside the React sidebar

### CODE REVIEW

**Comment by chrisdmacrae** [comment]
@ncphillips @spbyrne @kendallstrautman @dwalkr some things to note about stencil that made it hard to use for us until we knew them:

1. The react bindings will prefix all events with `on` in the react wrappers. E.g, an property called `click` decorated with stencil's `@Event()` decorator will be `onClick` in react code.
1. Stencil's decorators are _not_ typescript decorators. _Don't_ use decorators with Stencil.
1. Stencil only builds ESM in dev mode *(when passing the `--dev` flag)*. You need to test your production bundle separately in older browsers.
1. Stencil comes with Jest unit testing and Jest +_ Puppeteer integration testing in the box. You'll need to use it, because they patch a lot of stuff in JSDOM to make testing shadow DOM possible.
1. Stencil polyfills a bunch of things, such as: 
   - fetch
   - custom DOM events
   - css variables (use them)
1. Shadow DOM is not polyfilled in legacy browsers (old versions of chrome, firefox, and IE); instead the CSS is scoped using hashes to emulate the encapsulation.
1. The `globalStyle` and `globalScript` config options are compiled and bootstrapped in your bundle before the components intialize. Use these to:
   - Configure library-wide JS
   - Configure library-wide CSS vars
1. OOB Stencil just uses raw CSS. I would highly recommend installing `@stencil/postcss` and `postcss-preset-env` to be able to write modern CSS3 with nesting, variables, and much more.
1. Stencil is essentially a giant rollup plugin -- you can use virtually any rollup plugin with stencil.

Have fun! 🎉

**Comment by kendallstrautman** [comment]
This is so cool. Definitely some syntax to get used to! But its rad 🦄

**Comment by kendallstrautman** [comment]
I'm pretty amped on web components rn. This is gonna help Tina so much

**Comment by kendallstrautman** [comment]
I'm curious about what we see going in the `tinacms-ui` package. In looking at all the components we would need to convert to web components, it seems like a lot of bits and pieces are in `tinacms` and the fields in `@tinacms/core`. Is this `tinacms-ui` package going to be specific to more simple individual UI parts like buttons, loading dots, chevron etc.?

**Comment by kendallstrautman** [comment]
If and when we go full web components, would we move away from using `styled-components` since its react dependent? Obviously with web components we would get scoped styles and I think we can implement a sort of 'theming', but I guess I'm unclear how to approach dynamic styles with web components. I'm obviously a css-in-js fan, just curious if there's a way to fill in the gaps if we move away from it.

**Comment by kendallstrautman** [comment]
These comments may have been better suited for the forum or something. We can continue the convo elsewhere if needed!

**Comment by ncphillips** [comment]
This is a fine location for now. 

*Context for @erikras:* we're considering switching from React to Stencil so TinaCMS can truly be framework agnostic. Since TinaCMS relies on `final-form` I'm mentioning you here.

@kendallstrautman you're thinking a few steps ahead of me right now, so far I've just been trying to get a sense of how stuff works, but I'll give some of my thoughts:

I think `tinacms-ui` would end up being a design system that replaces `@tinacms/styles`. But that seems weird from a naming perspective I think eventually `@tinacms/styles` would be renamed  to `react-tinacms-ui` and wouldn't define anything, it would just be the auto-generated React adapters for `tinacms-ui`.

Yes, `styled-components` would go away with the switch to Stencil.

Switching `@tinacms/fields` and `@tinacms/form-builder` is the biggest challenge by far. Since `final-form` is well designed we can do it, but we would need to stop using `react-final-form` and create some kind of `stencil-final-form` adapter or something. Maybe we could enlist @erikras to help us out with that. 

Note: you mentioned fields being in `@tinacms/core`. That package doesn't actually know anything about fields. That's all in `@tinacms/fields`.

**Comment by chrisdmacrae** [comment]
@ncphillips @kendallstrautman feel free to ping me w/ general questions on web components and stencil -- I'll try helping out contributing to this is any way I can.

On dynamic theming -- rely on the platform. Ionic's (creators of stencil) ionic web component design system for ios and material design can serve as a great reference.

Stencil provides first-class support for creating design systems utilizing:

- Custom Elements
- Shadow DOM
  - Constructable stylesheets to share styles
- Modern CSS (using postcss and postcss-preset-env)
- CSS variables (polyfilled in IE11) via `globalStyle`
- And a theming feature using `getMode` and `setMode` from `@stencil/core`*

* The theming feature works by replacing `styleUrl` with `styleIUrls` in the component decorator, and passing it an object:

```
styleUrls: {
  light: "my-component.light.css",
  dark: "my-component.dark.css"
}
```

And then using `setMode` to provide a function for configuring the mode globally from the dom or setting it explicitly:

```
import { setMode } from "@stencil/core";

// hard set
setMode(() => return "light");

// Resolve from dom
// Dynamically recurses dom stencil elements for this data and returns a default
setMode((elm: any) => {
   let mode = "light";

    while (elm) {
      const elmMode = (elm as any).mode || elm.getAttribute('mode');

      if (elmMode) {
        mode = elmMode;
      }

      elm = elm.parentElement;
    }

    return mode;
  });
```

Finally using `getMode` to change the behaviour of a component based on the mode set.

```
import { getMode } from "@stencil/core";

...

private mode = getMode(this);

...

render() => (
  <Host class={{[mode]: true}}></Host>
);
```

**Comment by ncphillips** [comment]
@all-contributors please add @chrisdmacrae for questions and ideas

**Comment by ncphillips** [comment]
Closing for now. Fairly low on the priorities.

**Pull request closed without merging**
