### PR TITLE
Improve Table Alignment Icons

### LINKED ISSUE #709: Improve WYSIWYM icons
A few design tasks related to the toolbar and table icons:

 - [x] table alignment icons (#740)
 - [ ] Icon state whether a column is aligned or not (e.g. if a column is already centered, the center icon is seen as _active_, if I click on _left_ then, left icon moved to _active_ state. 
- [x] undo and redo icons (#708)
- [ ] insert media icons
- [ ] toolbar responsiveness? How should it behave in the sidebar? Wrap?

### PR DESCRIPTION
**Pull request by spbyrne**
* Improves text alignment icons

### CODE REVIEW

**Comment by DirtyF** [comment]
Are these the improved icons?

Capture d’écran 2020-02-12 à 15 13 51

**Comment by spbyrne** [comment]
Yup, that's them. They may still need a little more padding or adjustment.

**Comment by spbyrne** [comment]
I didn't make this branch off master, I may close this PR and create a new one.

**Comment by jpuri** [comment]
Hey @spbyrne , lets merge this soon.

**Pull request merged**
