### PR TITLE
chore: better error messages for tinafield

### PR DESCRIPTION
**Pull request by kenniaa**
I added proptypes to `TinaField` in order to improve the error message displayed when the `Component` prop is missing.

Now displays:
```
Warning: Failed prop type: The prop `Component` is marked as required in `y`, but its value is `undefined`.
```

Resolves https://github.com/tinacms/tinacms/issues/241

### CODE REVIEW

**Comment by kendallstrautman** [comment]
I tried to test this out on the demo-gatsby in the repo, but I'm unable to get the clean error message. What were your steps for testing?

**Comment by kendallstrautman** [comment]
@all-contributors please add @kenniaa for code

**Comment by kenniaa** [comment]
@kendallstrautman Hi! To test it, I took the `Component` prop off of `TinaField` in `blog-posts.js` https://github.com/tinacms/tinacms/blob/master/packages/demo-gatsby/src/templates/blog-post.js#L86

**Comment by ncphillips** [comment]
Thanks @kenniaa I've merged this into another branch so the CI can run. I'm sure it will pass. I will also test manually from there. 

We've been using Typescript for so long I totally forgot about proptypes. Thanks a lot for this 😄

**Pull request merged**
