### PR TITLE
feat: referential integrity

### PR DESCRIPTION
**Pull request by kldavis4**
# Problem

Document references don't get updated when the referenced document is updated / deleted

# Solution

Add referential integrity to ensure references are updated / removed

### CODE REVIEW

**Comment by ncn-ssw** [comment]
Hi @kldavis4,

✅ Tested correct - given that this change will bump the minor version of GraphQL, approval must await updating SQLite on TinaCloud.

The testing I conducted was as follows:

1. Pulled this PR into my TinaCMS repo
2. Ran `pnpm build && pnpm types` in the TinaCMS repo
3. Cloned the [TinaCloud Starter](https://github.com/tinacms/tina-cloud-starter) repository. I selected the TinaCloud Starter as the blog pages have a reference to the author items
5. Linked the TinaCloud Starter repository to the TinaCMS repo's (at)tinacms/cli and tinacms packages using `pnpm link`
6. In the TinaCloud Starter, deleted the `tina/tina-lock.json` file
7. In the TinaCloud Starter, ran `pnpm install`
8. In the TinaCloud Starter, ran `pnpm dev`
9. I confirmed that 'hasReference' can be found in newly generated `tina-lock.json` file to ensure that the changed schema code was being run
10. Went to `http://localhost:3000/admin/index.html#/collections/author/~` in a browser and deleted the 'Pedro' entry
12. I confirmed that the 'Pedro' entry was cleared from the author field of the item at `http://localhost:3000/admin/index.html#/~/posts/voteForPedro`
13. Went to `http://localhost:3000/admin/index.html#/collections/author/~` in a browser and renamed the file `content/authors/napolean.md` to `content/authors/napy.md`
14. I confirmed that the `Napolean` entry had been updated to `napy` at `http://localhost:3000/admin/index.html#/~/posts/anotherPost`

**Comment by kldavis4** [comment]
@ncn-ssw This should just be a patch bump to `@tinacms/graphql` as there is no breaking change (would be a minor w/ proper semver but this package doesn't adhere to it)

**Comment by ncn-ssw** [comment]
> @ncn-ssw This should just be a patch bump to `@tinacms/graphql` as there is no breaking change (would be a minor w/ proper semver but this package doesn't adhere to it)

My mistake - I misread the changeset.

**Review by ncn-ssw — APPROVED** [review]
🦙 Approved

**Pull request merged**
