### PR TITLE
hotfix: fix gatsby plugin builds

### PR DESCRIPTION
**Pull request by ncphillips**

### CODE REVIEW

**Comment by ncphillips** [comment]
Indeed. Thanks!

**Comment by bshackelford** [comment]
However, there are more exports that are needed in the `mdx and `json` packages similar to what we did with `remark`.

**Comment by bshackelford** [comment]
My bad for missing that @ncphillips. I'm happy to open a PR. Let me know.

**Comment by ncphillips** [comment]
That would be great appreciated! Just open it into this branch. I’ll hot fix it tomorrow morning.

**Pull request merged**
