### PR TITLE
fix: editor scrolling while changing mode

### PR DESCRIPTION
**Pull request by jpuri**
Fix scrolling in editor when changing mode.

Fixes https://github.com/tinacms/tinacms/issues/1225

### CODE REVIEW

**Comment by ncphillips** [comment]
It definitely works when going from Markdown to Wysiwyg but it's a bit funky going Wysiwyg to Markdown

https://www.loom.com/share/853bdc44e2c44ae4a4d95a803e54467c

**Comment by jpuri** [comment]
Hey @ncphillips : it did worked for page I tested:

scroll

May be its breaking with different page structure (your page has bug image on top). Let me check again.

**Comment by jpuri** [comment]
Hey @ncphillips:
scroll

It does works for me, can you re-build package and check.

**Comment by ncphillips** [comment]
Interesting. Yeah I just was seeing weird stuff on another branch and had to rebuild too. I'm satisfied by the gif haha

**Pull request merged**
