### PR TITLE
Add documentation for run Tina for development

### PR DESCRIPTION
**Pull request by hirvin-faria**
I'm adding documentation to help other contributors who want to run and contribute to the development of Tina.

Commenting how to edit tina packages, update and run the demo projects.

### CODE REVIEW

**Comment by DirtyF** [comment]
@hirvin-faria Please do sign our CLA 🙏

**Comment by hirvin-faria** [comment]
@DirtyF CLA signed. Thanks for notifying me

**Review by dwalkr — APPROVED** [review]

**Comment by dwalkr** [comment]
all-contributors add @hirvin-faria for docs

**Comment by dwalkr** [comment]
@all-contributors add @hirvin-faria for docs

**Pull request merged**
