### PR TITLE
chore: create separate components folder for all components

### PR DESCRIPTION
**Pull request by jpuri**
Create separate components folder.
Ref: https://github.com/tinacms/tinacms/issues/862#issuecomment-616667982

### CODE REVIEW

**Comment by jpuri** [comment]
Checking this issue @DirtyF .

**Comment by jpuri** [comment]
@DirtyF : it should be fixed after last commit.
Screenshot 2020-04-24 at 5 57 21 PM

**Comment by jpuri** [comment]
Hey @spbyrne : image upload modal position is breaking in this PR:

Screenshot 2020-04-24 at 6 41 09 PM

It appears to be related to code of `MenuButtonDropdown`, can you plz check.

**Comment by spbyrne** [comment]
I'm confused by a couple parts of this and I'm just looking for some clarity.

1. The `FormattingDropdown` component has become the `BlockControl` component, which used to be a file that (confusingly) contained `blockTool` (which was used by `FormattingDropdown`). Instead of `BlockControl` and `blockTool` maybe we should rename it 
 to `TitleControl` and `TitleOption` or something. Having them in separate files when they're so directly related doesn't seem necessary. 

2. The `ImageMenu` refs have been modified. Instead of creating a single `menuButtonRef` and passing it to both the `MenuButton` and `MenuButtonDropdown`, there's a large amount of additional logic added on lines 47-55 that doesn't seem necessary. 

The way the files were moved around combined with all the changes being in a single commit makes it hard to see what exactly changed. The diffs aren't very helpful.

I'll continue to troubleshoot the image modal issue.

**Comment by jpuri** [comment]
Hey @spbyrne : the issue appears related to this piece of [code](https://github.com/tinacms/tinacms/blob/master/packages/react-tinacms-editor/src/state/plugins/Menu/MenuComponents.tsx#L134).

I can try to debug and find exact cause.

Refactoring is actually WIP, it will me much clearer as I refactor code for plugins also.

**Comment by spbyrne** [comment]
I pushed a fix for the dropdown positioning. It was a combination of three things causing the issue:
1. The added ref logic in the `ImageMenu` component
2. The fact the offset measurement was taken from the offset child inside `MenuButtonDropdown`; this means only the first measurement would be accurate. This only worked because we were using `useMemo`, which would memorize the initial value. 
3. The use of `useMemo` caused issues when you closed a dropdown menu. The ref would be `null`, so `useMemo` would be triggered, but without a ref it would return 0. Now, it uses `useState` and only updates if there's a current ref available.

**Comment by spbyrne** [comment]
Unrelated but I think the link button in the toolbar should be disabled if no text is highlighted. Currently it pops up the modal in the default position, but with no text selected it's useless.

**Comment by jpuri** [comment]
Hey @spbyrne : I just pushed a commit to the PR which appears to be fixing this issue.

cc @DirtyF

**Comment by jpuri** [comment]
Hey @spbyrne : the fix for modal positioning works great 👍

**Comment by jpuri** [comment]
> Unrelated but I think the link button in the toolbar should be disabled if no text is highlighted. Currently it pops up the modal in the default position, but with no text selected it's useless.

Make sense, can you plz add this to issues of wysiwym.

**Comment by DirtyF** [comment]
Link button issue added in #1059

**Pull request merged**
