### PR TITLE
Display an error when node version < 14.18

### PR DESCRIPTION
**Pull request by Phoenix-Alpha**
close ENG-671

### CODE REVIEW

**Review by logan-anderson — CHANGES_REQUESTED** [review]
@Phoenix-Alpha instead of this being added in the bin directly I think it would make more sense to add it as a part of the chain for each "Command". 

[See the `checkOption` chain](https://github.com/tinacms/tinacms/blob/main/packages/@tinacms/cli/src/cmds/baseCmds.ts#L105) for an example

**Comment by Phoenix-Alpha** [comment]
@logan-anderson , the error happens when `cli/dist/index.js` is imported. Inside `cli/dist/index.js` there are some code which imports `node:path`. i.e.
image
I tried to put version checker inside the chain but `node:path` importing is called before my code as it is called as soon as the `cli/dist/index.js` is imported. So I needed to put version checking part before `cli/dist/index.js` is imported.

Please let me know your opinion.

**Comment by logan-anderson** [comment]
@Phoenix-Alpha that makes sense to me. @jeffsee55 What do you think?

**Comment by jeffsee55** [comment]
Makes sense to me.

**Review by jeffsee55 — APPROVED** [review]

**Pull request merged**
