### PR TITLE
build(lint): add prettier plugin to eslint

### PR DESCRIPTION
**Pull request by ncphillips**
Will issue warnings for failure to format with Prettier

### CODE REVIEW

**Comment by ncphillips** [comment]
We should see if we can get `prettier` working on your machine @kendallstrautman

**Comment by kendallstrautman** [comment]
Lol yesssssss

**Comment by ncphillips** [comment]
Ugh there's a lot of changes

https://github.com/tinacms/tinacms/compare/eslint-prettier...eslint-prettier-fix?expand=1

**Comment by kendallstrautman** [comment]
I think I figured it out 🎉

**Pull request closed without merging**
