### PR TITLE
feat(react-tinacms-inline): InlineBlocks children

### PR DESCRIPTION
**Pull request by Jaza**
Solves: https://community.tinacms.org/t/get-block-count-from-outside-inlineblocks/596

### CODE REVIEW

**Review by DirtyF — APPROVED** [review]
Thanks for the edit 🙏

**Comment by dwalkr** [comment]
Hey @Jaza! Thanks for the contribution! This looks good to me, and we should be able to get this into the next release of `react-tinacms-inline`.

As Logan mentioned in that forum thread, we plan to revisit Inline Editing wholesale in the (hopefully near) future, though we don't have an exact timeline for that just yet. We are generally avoiding any feature development on `react-tinacms-inline` right now, and this specific feature _may or may not_ make it into that future revision. But this is far off enough and not super clear just yet, so if this feature solves your problem there's no real harm in putting it out.

We definitely appreciate the contribution and discussion of your problem - this are things we will absolutely want to keep in mind!

**Review by dwalkr — APPROVED** [review]

**Comment by dwalkr** [comment]
@Jaza this is now available in prerelease `react-tinacms-inline@0.43.0-alpha.0`

**Comment by Jaza** [comment]
Cool, thanks for the run-down @dwalkr , and thanks for merging.

**Pull request merged**
