### PR TITLE
fix: remove namespace from db adapter

### PR DESCRIPTION
**Pull request by kldavis4**
namespace is only specified when calling createDatabase and not set on the adapter

### CODE REVIEW

**Comment by logan-anderson** [comment]
@kldavis4  What happens if the namespace is not passed? Will all indexes go to the same namespace?

**Comment by kldavis4** [comment]
> @kldavis4 What happens if the namespace is not passed? Will all indexes go to the same namespace?

There is a default namespace (for createDatabase)

**Comment by logan-anderson** [comment]
> > @kldavis4 What happens if the namespace is not passed? Will all indexes go to the same namespace?
> 
> There is a default namespace (for createDatabase)

If you are not using the namespace, switched branches,  changed content, and pushed up to Github it would build and over ride the content on `main` (Production deployment) Correct? 

I think it might be nice to keep passing the branch name as the namespace as it would avoid this issue.

**Comment by kldavis4** [comment]
> > > @kldavis4 What happens if the namespace is not passed? Will all indexes go to the same namespace?
> > 
> > 
> > There is a default namespace (for createDatabase)
> 
> If you are not using the namespace, switched branches, changed content, and pushed up to Github it would build and over ride the content on `main` (Production deployment) Correct?
> 
> I think it might be nice to keep passing the branch name as the namespace as it would avoid this issue.

I think you are misunderstanding the change - we already pass namespace to the createDatabase function. See: https://github.com/tinacms/tinacms/blob/self-host/examples/tina-self-hosted-demo/tina/database.ts#L21

If you set the collectionName to the branch on the mongo adapter, the user collection will be different for each branch.

**Comment by logan-anderson** [comment]
> > > > @kldavis4 What happens if the namespace is not passed? Will all indexes go to the same namespace?
> > > 
> > > 
> > > There is a default namespace (for createDatabase)
> > 
> > 
> > If you are not using the namespace, switched branches, changed content, and pushed up to Github it would build and over ride the content on `main` (Production deployment) Correct?
> > I think it might be nice to keep passing the branch name as the namespace as it would avoid this issue.
> 
> I think you are misunderstanding the change - we already pass namespace to the createDatabase function. See: https://github.com/tinacms/tinacms/blob/self-host/examples/tina-self-hosted-demo/tina/database.ts#L21
> 
> If you set the collectionName to the branch on the mongo adapter, the user collection will be different for each branch.

Gotcha, I thought that the namespace was done at the database / collection level. My bad

**Review by logan-anderson — APPROVED** [review]

**Comment by kldavis4** [comment]
> > > > > @kldavis4 What happens if the namespace is not passed? Will all indexes go to the same namespace?
> > > > 
> > > > 
> > > > There is a default namespace (for createDatabase)
> > > 
> > > 
> > > If you are not using the namespace, switched branches, changed content, and pushed up to Github it would build and over ride the content on `main` (Production deployment) Correct?
> > > I think it might be nice to keep passing the branch name as the namespace as it would avoid this issue.
> > 
> > 
> > I think you are misunderstanding the change - we already pass namespace to the createDatabase function. See: https://github.com/tinacms/tinacms/blob/self-host/examples/tina-self-hosted-demo/tina/database.ts#L21
> > If you set the collectionName to the branch on the mongo adapter, the user collection will be different for each branch.
> 
> Gotcha, I thought that the namespace was done at the database / collection level. My bad

Yeah, it used to be until the user collection was added

**Pull request merged**
