### PR TITLE
Export MediaStoreClass interface

### PR DESCRIPTION
**Pull request by Nopik**
The `MediaStoreClass` interface is private and used by public exports, which then breaks TS compilation for projects using Tina.

### CODE REVIEW

**Comment by jaschaio** [comment]
@brookjeynes-ssw @kldavis4 @ncn-ssw @jeffsee55 @JackDevAU could we get some attention to this?

It's a simple [6 character PR](https://github.com/tinacms/tinacms/pull/5284/files) that exports the `MediaStoreClass` without any downsides but helps us setting up a custom media store without any TS errors.

**Review by jeffsee55 — COMMENTED** [review]
@jaschaio or @Nopik this looks fine to me, but I'd like to understand how this is breaking TS compilation and how you're using it.

The reason for hesitation is that we'd like to narrow the surface area of our type exports.

**Comment by jaschaio** [comment]
Steps to replicate:

```
npx create-tina-app@latest
```

Choose npm, my-tina-app, NextJS starter

```
cd my-tina-app
npm install next-tinacms-s3
```

Edit the `tina/config.tsx`:

```diff
import { defineConfig } from "tinacms";

import Post from "./collection/post";
import Global from "./collection/global";
import Author from "./collection/author";
import Page from "./collection/page";

const config = defineConfig({
  clientId: process.env.NEXT_PUBLIC_TINA_CLIENT_ID!,
  branch:
    process.env.NEXT_PUBLIC_TINA_BRANCH! || // custom branch env override
    process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_REF! || // Vercel branch env
    process.env.HEAD!, // Netlify branch env
  token: process.env.TINA_TOKEN!,
  media: {
+    loadCustomStore: async () => {
+      const pack = await import("next-tinacms-s3");
+      return pack.TinaCloudS3MediaStore;
+    },
-    // If you wanted cloudinary do this
-    // loadCustomStore: async () => {
-    //   const pack = await import("next-tinacms-cloudinary");
-    //   return pack.TinaCloudCloudinaryMediaStore;
-    // },
-    // this is the config for the tina cloud media store
-    tina: {
-      publicFolder: "public",
-      mediaRoot: "uploads",
-    },
  },
  build: {
    publicFolder: "public", // The public asset folder for your framework
    outputFolder: "admin", // within the public folder
  },
  schema: {
    collections: [Page, Post, Author, Global],
  },
});

export default config;
```

Edit the `tsconfig.json` and turn on [`composite`](https://www.typescriptlang.org/tsconfig/#composite):

```diff
{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
+    "composite": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "exclude": ["node_modules"],
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"]
}
```

Go back to the config file and you will get this error:

```
Exported variable 'config' has or is using name 'MediaStoreClass' from external module "./my-tina-app/node_modules/tinacms/dist/index" but cannot be named.ts(4023)
```

Or just run `npx tsc` (but you will get a bunch more type errors as well):

```
tina/config.tsx:8:7 - error TS4023: Exported variable 'config' has or is using name 'MediaStoreClass' from external module "./my-tina-app/node_modules/tinacms/dist/index" but cannot be named.

8 const config = defineConfig({
        ~~~~~~
```

Repository: https://github.com/jaschaio/tina-mediastore-ts

**Comment by jeffsee55** [comment]
Thanks for that! Works for me

**Review by jeffsee55 — APPROVED** [review]

**Review by JackDevAU — APPROVED** [review]

**Pull request merged**
