### PR TITLE
feat(git): implement pushOnCommit option

### PR DESCRIPTION
**Pull request by lyleunderwood**
/cc #209 

@ncphillips Does this approach make sense to you?

### CODE REVIEW

**Comment by jamespohalloran** [comment]
Nice! I'm curious what others think the default for `PUSH_ON_COMMIT` should be. Maybe `false` until we validate it a bit more?

**Comment by lyleunderwood** [comment]
Right now it's just emulating the current behavior, so making it `false` would actually be a breaking change.

**Comment by jamespohalloran** [comment]
> Right now it's just emulating the current behavior, so making it false would actually be a breaking change.
Ah, my bad! you're totally right.

**Comment by dwalkr** [comment]
+1 for the separate `push` route! This is looking pretty good to me. What else needs to be done to get this out of draft status?

**Comment by ncphillips** [comment]
I'm feeling the same way. Nice job @lyleunderwood 👍

**Comment by lyleunderwood** [comment]
I was thinking about trying to tag some UI onto this, but based on discussions elsewhere I'll probably hold off. So I'll probably just update documentation and whatnot, then take it out of draft.

**Comment by lyleunderwood** [comment]
Hmm, I can't seem to find any documentation on the _current_ config options, so I guess I'm not gonna worry about that right now.

**Pull request merged**
