### PR TITLE
Custom buttons - issue#620

### PR DESCRIPTION
**Pull request by weibenfalk**
Just trying things out so far ... Probably needs refactoring and structuring

### CODE REVIEW

**Comment by ncphillips** [comment]
I'm going to close this for now @weibenfalk. I like where it's going, but the branch is getting really out of data and it's a bit power priority right now.

**Comment by weibenfalk** [comment]
Hey, that’s fine Nolan. I made this merely to show the concept of one way of solving it. 

If you want this solution I can do it for real now instead. So just tell me. =)

**Comment by ncphillips** [comment]
I think I'm liking this approach @weibenfalk if you want to take a crack at it feel free, or I can do so early next week (I'll make sure to co-author you in the commits).

**Comment by weibenfalk** [comment]
Glad you like it. Thanks. I spent some thinking on this and it makes sense
to be able to config it this way. There's not that many texts that can
change so it's a straightforward approach. Don't think I can manage to do
it this weekend but who knows ;) So if you start on it early next week
that's ok off course. It's your CMS ... haha ;)  Would love to be involved
and talk strategies and code if you will. =)

Den fre 21 feb. 2020 kl 21:35 skrev NCPhillips <notifications@github.com>:

**Pull request closed without merging**
